'use client';

import { useState } from 'react';
import { CheckCircle2, CreditCard, LockKeyhole, ReceiptText } from 'lucide-react';

export default function PaymentsPage() {
  const [paid, setPaid] = useState(false);
  return <div className="min-h-screen bg-gray-50 py-12"><div className="mx-auto max-w-4xl px-4"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#007B63]">Payment demo</p><h1 className="mt-2 text-3xl font-black">支払い管理</h1><p className="mt-2 text-sm text-gray-500">この画面はデモです。カード情報の保存や実際の請求は行いません。</p></div><div className="grid gap-6 md:grid-cols-[1fr_20rem]"><section className="rounded-3xl border border-gray-100 bg-white p-7"><div className="mb-6 flex items-center gap-3"><CreditCard className="text-[#007B63]" /><h2 className="font-bold">テストカード</h2></div><div className="space-y-4"><label className="block text-xs font-semibold text-gray-500">カード番号<input value="4242 4242 4242 4242" readOnly className="mt-2 w-full rounded-xl border border-gray-200 px-4 py-3 text-sm" /></label><div className="grid grid-cols-2 gap-3"><label className="block text-xs font-semibold text-gray-500">有効期限<input value="12 / 30" readOnly className="mt-2 w-full rounded-xl border border-gray-200 px-4 py-3 text-sm" /></label><label className="block text-xs font-semibold text-gray-500">CVC<input value="123" readOnly className="mt-2 w-full rounded-xl border border-gray-200 px-4 py-3 text-sm" /></label></div><button onClick={() => setPaid(true)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-[#007B63] py-3.5 text-sm font-bold text-white"><LockKeyhole className="h-4 w-4" />デモ支払いを確認</button>{paid && <p className="flex items-center gap-2 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700"><CheckCircle2 className="h-5 w-5" />デモ支払いが完了しました</p>}</div></section><aside className="rounded-3xl bg-gray-950 p-7 text-white"><ReceiptText className="h-6 w-6 text-[#00a882]" /><p className="mt-6 text-xs text-white/40">タスク報酬</p><p className="mt-1 text-3xl font-black">$45.00</p><div className="my-6 border-t border-white/10" /><div className="space-y-3 text-xs"><p className="flex justify-between"><span className="text-white/45">プラットフォーム利用料</span><span>$4.50</span></p><p className="flex justify-between font-bold"><span>合計</span><span>$49.50</span></p></div><p className="mt-8 text-[11px] leading-relaxed text-white/35">ランナーへの報酬は、タスク完了を確認するまで保留される想定です。</p></aside></div></div></div>;
}
