apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alta-go
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kaicyou2532/web_altago.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: alta-go
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
