apiVersion: apps/v1
kind: Deployment
metadata:
  name: alta-go
  namespace: alta-go
  labels:
    app.kubernetes.io/name: alta-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alta-go
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alta-go
    spec:
      containers:
        - name: alta-go
          image: ghcr.io/kaicyou2532/web_altago:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: alta-go-env
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
